= Jérôme Wacongne technical test by Skazy API Guide
Jérôme Wacongne;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[[overview]]
= Overview
API for Bao-Loc problem solutions

[[overview-http-verbs]]
== HTTP verbs

|===
| Verb | Usage

| `GET`
| Used to get resources from the system (read only)

| `PUT`
| Used to modify system state (update solutions)

| `DELETE`
| Used to delete solutions from thesystem
|===

[[overview-http-status-codes]]
== HTTP status codes

|===
| Status code | Usage

| `200 OK`
| The resource was found and returned

| `201 ACCEPTED`
| The system state was successfully changed (resource modified or deleted)

| `400 Bad Request`
| The request was malformed.

| `404 Not Found`
| The requested resource did not exist
|===

[[operations]]
= Operations

[[solutions]]
= Solutions

[[solutions-collection]]
== Solutions page
A `GET` request to `/solutions` will return a page of solutions

operation::solutions-collection[snippets='http-request,http-response']

[[solution]]
== Single solution
A specific solution can be accessed directly by issuing a `GET` request to `/solutions/{solutionId}`

operation::solution[snippets='response-fields,http-request,http-response']

[[solution-update]]
== Modify an existing solution
Individual solution modification is achieved with a `PUT` request to `/solutions/{solutionId}`

operation::solution-update[snippets='request-fields,http-request,http-response']

[[solution-delete]]
== Delete an existing solution
To remove a single solution from the database, send a `DELETE` request to `/solutions/{solutionId}`

operation::delete[snippets='http-request,http-response']

[[solution-delete-all]]
== Delete all existing solutions
A `DELETE` request to `/solutions` will drop all solutions from the DB

operation::delete-all[snippets='http-request,http-response']

