apiVersion: v1
kind: Service
metadata:
  labels:
    app: orders-api
  name: orders-api
spec:
  ports:
  - name: 4202-4202
    port: 4202
    protocol: TCP
    targetPort: 4202
  selector:
    app: orders-api
  type: LoadBalancer
status:
  loadBalancer: {}
