/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { GatewayConfiguration }                                     from '../configuration';



export interface BackChannelLogoutControllerApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: GatewayConfiguration;

    /**
     * 
     * 
     */
    backChannelLogout(extraHttpRequestParams?: any): Observable<{}>;

}
