/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { UserRolesDto } from '../model/models';


import { BaoLocConfiguration }                                     from '../configuration';



export interface UsersApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: BaoLocConfiguration;

    /**
     * 
     * 
     * @param username 
     */
    getUserRoles(username: string, extraHttpRequestParams?: any): Observable<UserRolesDto>;

}
