name: CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make Maven Wrapper executable
        if: contains(matrix.os, 'win') == false
        run: chmod +x ./mvnw
      - name: Package with Maven
        run: ./mvnw clean package --file pom.xml
      - name: Build Docker image
        run: docker build -t baoloc . --file Dockerfile
      - name: Tag Docker image for Dockerhub
        run: docker tag baoloc ch4mp/baoloc:0.0.1-SNAPSHOT
      - name: Tag Docker image for Azure
        run: docker tag baoloc baolocregistry.azurecr.io/baoloc:0.0.1-SNAPSHOT
      - name: Publish to Azure
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: baolocregistry.azurecr.io/baoloc:0.0.1-SNAPSHOT
          username: baolocregistry
          password: ${{ secrets.AZURE_PASSWORD }}
          registry: baolocregistry.azurecr.io
      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ch4mp/baoloc:0.0.1-SNAPSHOT
          username: ch4mp
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
