name: CI

on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Make Maven Wrapper executable
        if: contains(matrix.os, 'win') == false
        run: chmod +x ./api/mvnw

      - name: Package with Maven
        run: |
          cd ./api
          ./mvnw clean install
          ./mvnw spring-boot:build-image -DskipTests -pl bao-loc-api
          ./mvnw spring-boot:build-image -Pnative -DskipTests -pl gateway

      - name: Set VERSION environment variable
        run: |
          cd ./api
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Tag-Push gateway ${{ env.VERSION }}
        run: |
          docker tag bao-loc-gateway:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/bao-loc-gateway
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bao-loc-gateway

      - name: Docker Build-Tag-Push API ${{ env.VERSION }}
        run: |
          docker tag bao-loc-api:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/bao-loc-api-v1
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bao-loc-api-v1
      
      - name: Build Angular app
        run: |
          cd ./angular-ui
          npm run build

      - name: Docker Build-Tag-Push BFF Angular UI
        uses: docker/build-push-action@v4
        with:
          context: ./angular-ui
          file: ./angular-ui/Dockerfile-bff
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bao-loc-bff-ui

      - name: Docker Build-Tag-Push public-client Angular UI
        uses: docker/build-push-action@v4
        with:
          context: ./angular-ui
          file: ./angular-ui/Dockerfile-public-client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bao-loc-public-client-ui
      
      - name: Rollout Restart OVH demo-bao-loc
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.OVH_KUBECONFIG }} | base64 --decode > ${HOME}/.kube/config
          kubectl config use-context ovh
          kubectl rollout restart -n demo-bao-loc deployment.apps/bao-loc-bff-ui deployment.apps/bao-loc-public-client-ui deployment.apps/bao-loc-gateway deployment.apps/bao-loc-api-v1
